# Generated by Django 5.0.1 on 2024-05-05 10:33

import main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_custompermission_customrole'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.models.CustomUserManager()),
            ],
        ),
    ]
