# Generated by Django 5.0.1 on 2024-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_custompermission_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrole',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='roles', to='main.customrole'),
        ),
    ]
