# Generated by Django 5.0.1 on 2024-05-05 14:21

import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_customrole_users_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('artist', models.ManyToManyField(related_name='artworks', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', main.models.CustomUserManager()),
            ],
        ),
    ]
