# Generated by Django 5.0.1 on 2024-05-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_artwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artist',
            new_name='artists',
        ),
    ]
